if (getRversion() >= "2.15.1") {
  utils::globalVariables(c(
    ".",
    "codebook",
    "data_dictionary",
    "subject_label",
    "event_sequence",
    "verbal",
    "nonverbal",
    "min_age",
    "max_age",
    "raw_score",
    "iq",
    "ae",
    "sum_of_standard_scores",
    "verbal_raw_score",
    "nonverbal_raw_score",
    "crf_data_exclude_phi",
    "coenroll_exclude_phi",
    "dd_field_name",
    "dd_revision_field_value",
    "site_label",
    "Site",
    "items",
    "edc",
    "latest",
    "left_join",
    "full_join",
    ".f"
  ))
}


loni_file_names <- c(
  "ABC-DS IQ Worksheet",
  "ABC-DS Questionnaire Summary Sheet Controls",
  "ABC-DS Questionnaire Summary Sheet DS - Study Partner",
  "abcds biospecimen results",
  "ABCDS Proteomics Results Freeze5",
  "ABCDS targeted metabolomics combat adjusted",
  "ABCDS targeted metabolomics unadjusted",
  "ABCDS U01-U19 Codebook",
  "ABCDS U01-U19 Data Dictionary",
  "AD8 Dementia Screening Interview Controls",
  "Adverse Events Log",
  "Age at Event and Latency Controls",
  "Age at Event and Latency",
  "Amyloid PET Scan Information Controls",
  "Amyloid PET Scan Information",
  "ApoE Genotyping Results Controls",
  "ApoE Genotyping Results",
  "Cancellation Task",
  "Cats and Dogs Task",
  "Centiloid Analysis of PET Data Controls",
  "Centiloid Analysis of PET Data",
  "Consensus",
  "Consent Tracking Participant Controls",
  "Consent Tracking Participant",
  "Control Participant Information Controls",
  "CSF Results",
  "Cued Recall",
  "Down Syndrome Mental Status Exam",
  "Down Syndrome Neuropsych Information Sheet",
  "Enrollment Verification Controls",
  "Enrollment Verification",
  "Family History Controls",
  "Family History",
  "FDG PET Scan Information Controls",
  "FDG PET Scan Information",
  "Haxby Extended Block Design",
  "Health History Controls",
  "Health History",
  "Health History Followup Controls",
  "Health History Followup",
  "Karyotyping",
  "Medications Health History Worksheet Controls",
  "Medications Health History Worksheet",
  "Montreal Cognitive Assessment Controls",
  "MRI Scan Information Controls",
  "MRI Scan Information",
  "Neuropathology Controls",
  "Neuropathology",
  "Neuropsychiatric Inventory",
  "NTG Study Partner Concerns",
  "Participant Demographics Controls",
  "Participant Demographics",
  "Participant Registration Controls",
  "Participant Registration",
  "Physical and Neurological Exam",
  "Premorbid Functioning Level",
  "Purdue Pegboard",
  "RADD Hand Movements Imitation",
  "Registry Controls",
  "Registry",
  "Reiss Screen for Maladaptive Behavior",
  "Safety labs Results",
  "Sample Collection Blood Controls",
  "Sample Collection Blood",
  "Sample Collection CSF Controls",
  "Sample Collection CSF",
  "Sibling Control Neuropsych Information Sheet Controls",
  "Site ID List Controls",
  "Site ID List",
  "Stress Index",
  "Study Partner Worksheet",
  "Study Visits Summary Controls",
  "Study Visits Summary",
  "Tau PET Scan Information Controls",
  "Tau PET Scan Information",
  "The Dementia Questionnaire for People with Learning Disabilities",
  "Tinetti Assessment Tool Gait Test",
  "TRC-DS Coenrollment",
  "Verbal Fluency",
  "Vineland Adaptive Behavior Scale 3",
  "Visual-Motor Integration",
  "WISC-IV Block Design"
)
